#cloud-config
autoinstall:
  version: 1
  source:
    id: ubuntu-desktop-minimal
  identity:
    hostname: placeholder
    realname: "Usuario de Suporte"
    username: suporte
    password: '$y$j9T$goE4AFcfqagaSOkTkgKFM1$tD2z6JVPkT/kG5UygXfkEL9UVXcnNowAaLsyWK49Vs6'
  locale: "en_US.UTF-8"
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  packages:
    - libreoffice
    - git
    - wget
    - landscape-client
    - dmidecode
  snaps:
    - name: code
      channel: stable
      classic: false
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  early-commands:
    - mkdir -p /etc/cryptsetup-keys.d
    - dd if=/dev/urandom of=/etc/cryptsetup-keys.d/root.key bs=1024 count=4
    - chmod 600 /etc/cryptsetup-keys.d/root.key
    - |
      SERIAL=$(dmidecode -s system-serial-number | tr '[:upper:]' '[:lower:]')
      HOSTNAME="host-${SERIAL}"

      echo "Definindo hostname como ${HOSTNAME}"
      curtin in-target --target /target -- bash -c "
      echo "${HOSTNAME}" > /etc/hostname
      sed -i "s/127.0.1.1.*/127.0.1.1 ${HOSTNAME}/" /etc/hosts
      hostnamectl set-hostname '$(HOSTNAME)'
      "
  late-commands:
    - curtin in-target --target /target -- bash -c 'sudo landscape-config --computer-title "${HOSTNAME}" --account-name "vanildo-franca"
  shutdown: reboot