#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: placeholder
    realname: "Usuario de Suporte"
    username: suporte
    password: '$6$JWgq58nxhpyzsKJc$U0NS0l7TsI7LB5SaiR0r7FAgDNNcH/vfNuofT15qRb1JGPc7gKEIrN2x8x.JyQ7Z9lHA.CCwYmMmsJ2byJAx2/'
  locale: "en_US.UTF-8"
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  packages:
    - libreoffice
    - git
    - wget
    - landscape-client
    - dmidecode
  snaps:
    - name: code
      channel: stable
      classic: true
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  late-commands:
    - |
      curtin in-target -- sh -c '
      SERIAL=$(dmidecode -s system-serial-number | tr "[:upper:]" "[:lower:]" | xargs)

      # Valida se é vazio ou "not specified"
      if [ -z "$SERIAL" ] || [ "$SERIAL" = "not" ] || [ "$SERIAL" = "specified" ] || [ "$SERIAL" = "notspecified" ] || [ "$SERIAL" = "not specified" ]; then
          # Gera um UUID e pega o primeiro bloco (8 caracteres)
          SERIAL=$(cat /proc/sys/kernel/random/uuid | cut -d"-" -f1)
      fi
      
      HOSTNAME="voltz-${SERIAL}"
      
      echo "Configurando hostname para: $HOSTNAME"
      hostnamectl set-hostname "$HOSTNAME"
      echo "$HOSTNAME" > /etc/hostname
      sed -i "s/placeholder/$HOSTNAME/g" /etc/hosts

      # 2. Configuração e Registro do Landscape
      # O comando abaixo configura e registra o cliente usando o novo hostname
      landscape-config --silent \
          --computer-title "$HOSTNAME" \
          --account-name "vanildo-franca" \
          --url "https://landscape.canonical.com/message-system" \
          --ping-url "https://landscape.canonical.com/ping" \
          --registration-key "Energisa" \
          --include-manager-plugins "ScriptExecution" || true
      '
  #  - curtin in-target -- wget https://repo2.xxxxx.com/debian/dists/stable/main/binary-all/xxxx.deb
  #  - curtin in-target -- dpkg -i ./xxxxx.deb
  #  - curtin in-target -- apt update
  #  - curtin in-target -- apt install -y 
  shutdown: reboot
